// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestaurantReservation.Infrastructure.EF.Data;

#nullable disable

namespace RestaurantReservation.Infrastructure.EF.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestaurantReservation.Domain.CustomerAggregate.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_by");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("RestaurantReservation.Domain.ReservationAggregate.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("Occupants")
                        .HasColumnType("integer")
                        .HasColumnName("occupants");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("date")
                        .HasColumnName("reservation_date");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uuid")
                        .HasColumnName("table_id");

                    b.HasKey("Id")
                        .HasName("pk_reservations");

                    b.HasIndex("TableId")
                        .HasDatabaseName("ix_reservations_table_id");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("RestaurantReservation.Domain.RestaurantAggregate.Models.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("WebSite")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("web_site");

                    b.HasKey("Id")
                        .HasName("pk_restaurants");

                    b.ToTable("restaurants", (string)null);
                });

            modelBuilder.Entity("RestaurantReservation.Domain.RestaurantAggregate.Models.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("table_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id")
                        .HasName("pk_tables");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_tables_restaurant_id");

                    b.ToTable("tables", (string)null);
                });

            modelBuilder.Entity("RestaurantReservation.Domain.RestaurantAggregate.ValueObjects.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<long?>("LastModifiedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_reviews_restaurant_id");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("RestaurantReservation.Domain.CustomerAggregate.Models.Customer", b =>
                {
                    b.OwnsOne("RestaurantReservation.Domain.Common.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("email");

                            b1.HasKey("CustomerId")
                                .HasName("pk_customers");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId")
                                .HasConstraintName("fk_customers_customers_customer_id");
                        });

                    b.OwnsOne("RestaurantReservation.Domain.CustomerAggregate.ValueObjects.CustomerName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("CustomerId")
                                .HasName("pk_customers");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId")
                                .HasConstraintName("fk_customers_customers_customer_id");
                        });

                    b.OwnsMany("RestaurantReservation.Domain.ReservationAggregate.ValueObjects.ReservationId", "Reservations", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_reservation_id");

                            b1.HasKey("Id")
                                .HasName("pk_customer_reservation_ids");

                            b1.HasIndex("CustomerId")
                                .HasDatabaseName("ix_customer_reservation_ids_customer_id");

                            b1.ToTable("customer_reservation_ids", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId")
                                .HasConstraintName("fk_customer_reservation_ids_customers_customer_id");
                        });

                    b.OwnsMany("RestaurantReservation.Domain.RestaurantAggregate.ValueObjects.RestaurantId", "FavouriteRestaurants", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_id");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("customer_favourite_restaurant_id");

                            b1.HasKey("Id")
                                .HasName("pk_customer_favourite_restaurant_ids");

                            b1.HasIndex("CustomerId")
                                .HasDatabaseName("ix_customer_favourite_restaurant_ids_customer_id");

                            b1.ToTable("customer_favourite_restaurant_ids", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CustomerId")
                                .HasConstraintName("fk_customer_favourite_restaurant_ids_customers_customer_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FavouriteRestaurants");

                    b.Navigation("FullName")
                        .IsRequired();

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RestaurantReservation.Domain.ReservationAggregate.Models.Reservation", b =>
                {
                    b.HasOne("RestaurantReservation.Domain.RestaurantAggregate.Models.Table", null)
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_tables_table_id");
                });

            modelBuilder.Entity("RestaurantReservation.Domain.RestaurantAggregate.Models.Restaurant", b =>
                {
                    b.OwnsOne("RestaurantReservation.Domain.RestaurantAggregate.ValueObjects.WorkTime", "WorkTime", b1 =>
                        {
                            b1.Property<Guid>("RestaurantId")
                                .HasColumnType("uuid")
                                .HasColumnName("restaurant_id");

                            b1.HasKey("RestaurantId")
                                .HasName("pk_restaurants");

                            b1.ToTable("restaurants");

                            b1.WithOwner()
                                .HasForeignKey("RestaurantId")
                                .HasConstraintName("fk_restaurants_restaurants_restaurant_id");

                            b1.OwnsOne("RestaurantReservation.Domain.RestaurantAggregate.ValueObjects.WorkingHours", "Friday", b2 =>
                                {
                                    b2.Property<Guid>("WorkTimeRestaurantId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("restaurant_id");

                                    b2.Property<TimeSpan>("ClosingTime")
                                        .HasColumnType("interval")
                                        .HasColumnName("friday_closing_time");

                                    b2.Property<TimeSpan>("OpeningTime")
                                        .HasColumnType("interval")
                                        .HasColumnName("friday_opening_time");

                                    b2.HasKey("WorkTimeRestaurantId")
                                        .HasName("pk_restaurants");

                                    b2.ToTable("restaurants");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkTimeRestaurantId")
                                        .HasConstraintName("fk_restaurants_restaurants_restaurant_id");
                                });

                            b1.OwnsOne("RestaurantReservation.Domain.RestaurantAggregate.ValueObjects.WorkingHours", "Monday", b2 =>
                                {
                                    b2.Property<Guid>("WorkTimeRestaurantId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("restaurant_id");

                                    b2.Property<TimeSpan>("ClosingTime")
                                        .HasColumnType("interval")
                                        .HasColumnName("monday_closing_time");

                                    b2.Property<TimeSpan>("OpeningTime")
                                        .HasColumnType("interval")
                                        .HasColumnName("monday_opening_time");

                                    b2.HasKey("WorkTimeRestaurantId")
                                        .HasName("pk_restaurants");

                                    b2.ToTable("restaurants");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkTimeRestaurantId")
                                        .HasConstraintName("fk_restaurants_restaurants_restaurant_id");
                                });

                            b1.OwnsOne("RestaurantReservation.Domain.RestaurantAggregate.ValueObjects.WorkingHours", "Saturday", b2 =>
                                {
                                    b2.Property<Guid>("WorkTimeRestaurantId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("restaurant_id");

                                    b2.Property<TimeSpan>("ClosingTime")
                                        .HasColumnType("interval")
                                        .HasColumnName("saturday_closing_time");

                                    b2.Property<TimeSpan>("OpeningTime")
                                        .HasColumnType("interval")
                                        .HasColumnName("saturday_opening_time");

                                    b2.HasKey("WorkTimeRestaurantId")
                                        .HasName("pk_restaurants");

                                    b2.ToTable("restaurants");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkTimeRestaurantId")
                                        .HasConstraintName("fk_restaurants_restaurants_restaurant_id");
                                });

                            b1.OwnsOne("RestaurantReservation.Domain.RestaurantAggregate.ValueObjects.WorkingHours", "Sunday", b2 =>
                                {
                                    b2.Property<Guid>("WorkTimeRestaurantId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("restaurant_id");

                                    b2.Property<TimeSpan>("ClosingTime")
                                        .HasColumnType("interval")
                                        .HasColumnName("sunday_closing_time");

                                    b2.Property<TimeSpan>("OpeningTime")
                                        .HasColumnType("interval")
                                        .HasColumnName("sunday_opening_time");

                                    b2.HasKey("WorkTimeRestaurantId")
                                        .HasName("pk_restaurants");

                                    b2.ToTable("restaurants");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkTimeRestaurantId")
                                        .HasConstraintName("fk_restaurants_restaurants_restaurant_id");
                                });

                            b1.OwnsOne("RestaurantReservation.Domain.RestaurantAggregate.ValueObjects.WorkingHours", "Thursday", b2 =>
                                {
                                    b2.Property<Guid>("WorkTimeRestaurantId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("restaurant_id");

                                    b2.Property<TimeSpan>("ClosingTime")
                                        .HasColumnType("interval")
                                        .HasColumnName("thursday_closing_time");

                                    b2.Property<TimeSpan>("OpeningTime")
                                        .HasColumnType("interval")
                                        .HasColumnName("thursday_opening_time");

                                    b2.HasKey("WorkTimeRestaurantId")
                                        .HasName("pk_restaurants");

                                    b2.ToTable("restaurants");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkTimeRestaurantId")
                                        .HasConstraintName("fk_restaurants_restaurants_restaurant_id");
                                });

                            b1.OwnsOne("RestaurantReservation.Domain.RestaurantAggregate.ValueObjects.WorkingHours", "Tuesday", b2 =>
                                {
                                    b2.Property<Guid>("WorkTimeRestaurantId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("restaurant_id");

                                    b2.Property<TimeSpan>("ClosingTime")
                                        .HasColumnType("interval")
                                        .HasColumnName("tuesday_closing_time");

                                    b2.Property<TimeSpan>("OpeningTime")
                                        .HasColumnType("interval")
                                        .HasColumnName("tuesday_opening_time");

                                    b2.HasKey("WorkTimeRestaurantId")
                                        .HasName("pk_restaurants");

                                    b2.ToTable("restaurants");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkTimeRestaurantId")
                                        .HasConstraintName("fk_restaurants_restaurants_restaurant_id");
                                });

                            b1.OwnsOne("RestaurantReservation.Domain.RestaurantAggregate.ValueObjects.WorkingHours", "Wednesday", b2 =>
                                {
                                    b2.Property<Guid>("WorkTimeRestaurantId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("restaurant_id");

                                    b2.Property<TimeSpan>("ClosingTime")
                                        .HasColumnType("interval")
                                        .HasColumnName("wednesday_closing_time");

                                    b2.Property<TimeSpan>("OpeningTime")
                                        .HasColumnType("interval")
                                        .HasColumnName("wednesday_opening_time");

                                    b2.HasKey("WorkTimeRestaurantId")
                                        .HasName("pk_restaurants");

                                    b2.ToTable("restaurants");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkTimeRestaurantId")
                                        .HasConstraintName("fk_restaurants_restaurants_restaurant_id");
                                });

                            b1.Navigation("Friday")
                                .IsRequired();

                            b1.Navigation("Monday")
                                .IsRequired();

                            b1.Navigation("Saturday")
                                .IsRequired();

                            b1.Navigation("Sunday")
                                .IsRequired();

                            b1.Navigation("Thursday")
                                .IsRequired();

                            b1.Navigation("Tuesday")
                                .IsRequired();

                            b1.Navigation("Wednesday")
                                .IsRequired();
                        });

                    b.Navigation("WorkTime")
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantReservation.Domain.RestaurantAggregate.Models.Table", b =>
                {
                    b.HasOne("RestaurantReservation.Domain.RestaurantAggregate.Models.Restaurant", "Restaurant")
                        .WithMany("Tables")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tables_restaurants_restaurant_id");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantReservation.Domain.RestaurantAggregate.ValueObjects.Review", b =>
                {
                    b.HasOne("RestaurantReservation.Domain.RestaurantAggregate.Models.Restaurant", "Restaurant")
                        .WithMany("Reviews")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_restaurants_restaurant_id");

                    b.OwnsOne("RestaurantReservation.Domain.ReservationAggregate.Models.Rating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("ReviewId")
                                .HasColumnType("uuid")
                                .HasColumnName("review_id");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("rating");

                            b1.HasKey("ReviewId")
                                .HasName("pk_reviews");

                            b1.ToTable("reviews");

                            b1.WithOwner()
                                .HasForeignKey("ReviewId")
                                .HasConstraintName("fk_reviews_reviews_review_id");
                        });

                    b.Navigation("Rating")
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("RestaurantReservation.Domain.RestaurantAggregate.Models.Restaurant", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("RestaurantReservation.Domain.RestaurantAggregate.Models.Table", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
